version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-ems
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: paradox61
      MYSQL_DATABASE: employee_management_system
    ports:
      - "3307:3306"  # Host 3307 â†’ container 3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: springboot-ems
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/employee_management_system?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: paradox61

volumes:
  mysql_data:
